export const TURNSTILE_AUTH_PAGE_LOAD_TIMEOUT_MS = 20_000;

export const TURNSTILE_SCRIPT_MAX_RETRIES = 2;
export const TURNSTILE_SCRIPT_RETRY_BASE_DELAY_MS = 1_200;

export const TURNSTILE_VERIFY_REQUEST_TIMEOUT_MS = 10_000;
