/**
 * Curated towns / suburbs per city per province.
 * Used as auto-complete suggestions — users can still type
 * any value not in this list.
 *
 * Structure:  province → city → towns[]
 */

const SA_TOWNS: Record<string, Record<string, string[]>> = {
  /* ── Gauteng ─────────────────────────────────────────── */
  Gauteng: {
    Johannesburg: [
      "Braamfontein",
      "Hillbrow",
      "Yeoville",
      "Melville",
      "Auckland Park",
      "Brixton",
      "Fordsburg",
      "Newtown",
      "Marshalltown",
      "Jeppestown",
      "Berea",
      "Doornfontein",
      "Fairlands",
      "Northcliff",
      "Linden",
      "Emmarentia",
      "Parktown",
      "Parkview",
      "Rosebank",
      "Houghton",
      "Killarney",
      "Craighall",
      "Hyde Park",
      "Rivonia",
      "Bryanston",
      "Fourways",
      "Lonehill",
      "Sunninghill",
      "Woodmead",
      "Buccleuch",
      "Modderfontein",
      "Edenvale",
      "Bedfordview",
      "Kensington",
      "Observatory",
      "Orange Grove",
      "Norwood",
      "Cyrildene",
      "Bez Valley",
      "Malvern",
      "Sydenham",
      "Rosettenville",
      "Turffontein",
      "Booysens",
      "Mondeor",
      "Meredale",
      "Glenvista",
      "Bassonia",
      "Mulbarton",
      "Ormonde",
      "Naturena",
      "Eldorado Park",
      "Lenasia",
      "Lenasia South",
      "Ennerdale",
      "Orange Farm",
      "Diepsloot",
      "Cosmo City",
      "Honeydew",
      "Little Falls",
      "Bromhof",
      "Kya Sand",
      "Olivedale",
      "Ferndale",
      "Randpark Ridge",
      "Kensington B",
      "Greenside",
    ],
    Pretoria: [
      "Arcadia",
      "Hatfield",
      "Sunnyside",
      "Brooklyn",
      "Menlo Park",
      "Muckleneuk",
      "Lynnwood",
      "Waterkloof",
      "Groenkloof",
      "Erasmuskloof",
      "Faerie Glen",
      "Garsfontein",
      "Moreleta Park",
      "Elardus Park",
      "Lyttelton",
      "Irene",
      "Rietondale",
      "Riviera",
      "Gezina",
      "Sinoville",
      "Montana",
      "Wonderboom",
      "Akasia",
      "Rosslyn",
      "Atteridgeville",
      "Mamelodi",
      "Hammanskraal",
      "Silverton",
      "Villieria",
      "Capital Park",
      "Daspoort",
      "Danville",
      "Pretoria North",
      "Pretoria West",
      "Pretoria Gardens",
      "Booysens (PTA)",
      "Salvokop",
      "Hercules",
    ],
    Centurion: [
      "Centurion CBD",
      "Eldoraigne",
      "Wierdapark",
      "Zwartkop",
      "Hennopspark",
      "Die Hoewes",
      "Clubview",
      "Eco Park",
      "Highveld",
      "Rooihuiskraal",
      "Wierda Park",
      "Erasmusrand",
      "The Reeds",
      "Jean Acres",
      "Cornwall Hill",
      "Southdowns",
    ],
    Sandton: [
      "Sandton CBD",
      "Sandhurst",
      "Sandown",
      "Morningside",
      "Illovo",
      "Atholl",
      "Inanda",
      "Wendywood",
      "Marlboro",
      "Strathavon",
      "Benmore",
      "Kramerville",
      "Parkmore",
      "Hurlingham",
      "Rivonia",
      "Gallo Manor",
    ],
    Soweto: [
      "Orlando East",
      "Orlando West",
      "Diepkloof",
      "Dobsonville",
      "Meadowlands",
      "Protea Glen",
      "Pimville",
      "Klipspruit",
      "Naledi",
      "Zola",
      "Jabulani",
      "Mofolo",
      "Dube",
      "Chiawelo",
      "Mapetla",
      "Phiri",
      "Senoane",
      "Rockville",
      "Tladi",
      "Moletsane",
      "Emdeni",
      "White City",
      "Power Park",
    ],
    Midrand: [
      "Midrand CBD",
      "Halfway House",
      "Glen Austin",
      "Halfway Gardens",
      "Carlswald",
      "Vorna Valley",
      "Noordwyk",
      "Commercia",
      "Kyalami",
      "Waterfall",
      "Sagewood",
      "Summerset Estate",
    ],
    Randburg: [
      "Randburg CBD",
      "Ferndale",
      "Fontainebleau",
      "Kensington B",
      "Bordeaux",
      "Blairgowrie",
      "Linden",
      "Roosevelt Park",
      "Northriding",
      "Sundowner",
      "Windsor",
    ],
    Roodepoort: [
      "Roodepoort CBD",
      "Florida",
      "Florida Glen",
      "Constantia Kloof",
      "Wilgeheuwel",
      "Strubens Valley",
      "Horison",
      "Ruimsig",
      "Helderkruin",
      "Honeydew Ridge",
      "Radiokop",
    ],
    Boksburg: [
      "Boksburg CBD",
      "Bartlett",
      "Sunward Park",
      "Jet Park",
      "Cason",
      "Rynfield",
      "Reiger Park",
      "Parkrand",
      "Comet",
      "Witfield",
    ],
    Benoni: [
      "Benoni CBD",
      "Northmead",
      "Farrarmere",
      "Lakefield",
      "Rynfield",
      "Petit",
      "Brentwood Park",
      "Norton",
      "Airfield",
    ],
    "Kempton Park": [
      "Kempton Park CBD",
      "Glen Marais",
      "Birch Acres",
      "Aston Manor",
      "Van Riebeeck Park",
      "Pomona",
      "Cresslawn",
      "Spartan",
      "Bredell",
      "Bonaero Park",
    ],
    Germiston: [
      "Germiston CBD",
      "Lambton",
      "Primrose",
      "Delville",
      "Dinwiddie",
      "Elandsfontein",
      "Driehoek",
      "Elsburg",
    ],
    Springs: ["Springs CBD", "Selection Park", "Strubenvale", "Geduld", "Casseldale", "Welgedacht"],
    Alberton: [
      "Alberton CBD",
      "New Redruth",
      "Brackendowns",
      "Verwoerdpark",
      "Randhart",
      "Meyersdal",
      "Alberante",
    ],
    Krugersdorp: [
      "Krugersdorp CBD",
      "Krugersdorp North",
      "Monument",
      "Mindalore",
      "Dan Pienaarville",
      "Kenmare",
    ],
    Vereeniging: [
      "Vereeniging CBD",
      "Three Rivers",
      "Duncanville",
      "Unitas Park",
      "Leeuhof",
      "Peacehaven",
      "Arcon Park",
    ],
    Vanderbijlpark: [
      "Vanderbijlpark CBD",
      "SE 1",
      "SE 2",
      "SE 3",
      "CE 1",
      "CW",
      "Bophelong",
      "Boipatong",
    ],
  },

  /* ── Western Cape ───────────────────────────────────────── */
  "Western Cape": {
    "Cape Town": [
      "City Bowl",
      "Gardens",
      "Tamboerskloof",
      "Oranjezicht",
      "Vredehoek",
      "Woodstock",
      "Observatory",
      "Mowbray",
      "Rondebosch",
      "Claremont",
      "Newlands",
      "Kenilworth",
      "Wynberg",
      "Plumstead",
      "Constantia",
      "Tokai",
      "Bergvliet",
      "Retreat",
      "Muizenberg",
      "Fish Hoek",
      "Simons Town",
      "Kalk Bay",
      "Mitchell's Plain",
      "Khayelitsha",
      "Gugulethu",
      "Langa",
      "Athlone",
      "Manenberg",
      "Hanover Park",
      "Grassy Park",
      "Ottery",
      "Lansdowne",
      "Crawford",
      "Rondebosch East",
      "Pinelands",
      "Thornton",
      "Goodwood",
      "Parow",
      "Bellville South",
      "Elsies River",
      "Bishop Lavis",
      "Bonteheuwel",
      "Lentegeur",
      "Green Point",
      "Sea Point",
      "Camps Bay",
      "Clifton",
      "Bantry Bay",
      "Fresnaye",
      "Mouille Point",
      "V&A Waterfront",
      "Century City",
      "Milnerton",
      "Table View",
      "Bloubergstrand",
      "Parklands",
      "Sunningdale",
      "Bothasig",
      "Edgemead",
      "Durbanville",
      "Kraaifontein",
      "Brackenfell",
      "Kuilsrivier",
      "Delft",
      "Blue Downs",
      "Eerste River",
      "Strand",
      "Gordon's Bay",
      "Macassar",
      "Somerset West",
    ],
    Stellenbosch: [
      "Stellenbosch CBD",
      "Die Boord",
      "Paradyskloof",
      "Dalsig",
      "Welgevonden",
      "Idas Valley",
      "Kayamandi",
      "Cloetesville",
      "Franschhoek",
    ],
    Paarl: ["Paarl CBD", "Courtrai", "Klein Drakenstein", "Mbekweni", "Dal Josafat", "Paarl East"],
    George: [
      "George CBD",
      "Blanco",
      "Heatherlands",
      "Pacaltsdorp",
      "Thembalethu",
      "Wilderness",
      "Herolds Bay",
    ],
    Knysna: ["Knysna CBD", "The Heads", "Leisure Isle", "Brenton-on-Sea", "Sedgefield"],
    "Mossel Bay": ["Mossel Bay CBD", "Hartenbos", "Dana Bay", "Great Brak River", "Pinnacle Point"],
    Worcester: ["Worcester CBD", "Zwelethemba", "Avian Park", "Hex River"],
    Hermanus: ["Hermanus CBD", "Onrus River", "Vermont", "Hawston", "Kleinmond"],
    Franschhoek: ["Franschhoek CBD", "La Motte", "Groendal"],
    "Somerset West": [
      "Somerset West CBD",
      "Helderberg",
      "Strand",
      "Gordon's Bay",
      "Sir Lowry's Pass",
    ],
    Bellville: ["Bellville CBD", "Oakdale", "Loevenstein", "Kenridge", "Welgemoed", "De Tyger"],
    Durbanville: [
      "Durbanville CBD",
      "Vierlanden",
      "Sonstraal Heights",
      "Pinehurst",
      "Goedemoed",
      "Amanda Glen",
    ],
    Malmesbury: ["Malmesbury CBD", "Abbotsdale", "Wesbank"],
  },

  /* ── KwaZulu-Natal ─────────────────────────────────────── */
  "KwaZulu-Natal": {
    Durban: [
      "Durban CBD",
      "Berea",
      "Morningside",
      "Musgrave",
      "Glenwood",
      "Umbilo",
      "Overport",
      "Sydenham",
      "Sherwood",
      "Cato Manor",
      "uMlazi",
      "KwaMashu",
      "Inanda",
      "Ntuzuma",
      "Tongaat",
      "Verulam",
      "Phoenix",
      "Chatsworth",
      "Merebank",
      "Isipingo",
      "Amanzimtoti",
      "Warner Beach",
      "Wentworth",
      "Bluff",
      "North Beach",
      "South Beach",
      "Point",
      "La Lucia",
      "Umhlanga Rocks",
      "Mount Edgecombe",
      "Hillcrest",
      "Pinetown",
      "Kloof",
      "Westville",
      "Queensburgh",
      "Malvern",
      "Montclair",
      "Yellowwood Park",
      "Woodlands",
    ],
    Pietermaritzburg: [
      "Pietermaritzburg CBD",
      "Scottsville",
      "Northdale",
      "Montrose",
      "Hayfields",
      "Chase Valley",
      "Wembley",
      "Athlone",
      "Edendale",
      "Imbali",
      "Sobantu",
    ],
    "Richards Bay": [
      "Richards Bay CBD",
      "Meerensee",
      "Arboretum",
      "Birdswood",
      "Aquadene",
      "Brackenham",
    ],
    Newcastle: [
      "Newcastle CBD",
      "Madadeni",
      "Osizweni",
      "Arbor Park",
      "Barry Hertzog",
      "Lennoxton",
    ],
    Umhlanga: [
      "Umhlanga Ridge",
      "Umhlanga Rocks",
      "La Lucia",
      "Prestondale",
      "Herrwood",
      "Cornubia",
    ],
    Ballito: ["Ballito CBD", "Shaka's Rock", "Salt Rock", "Zimbali", "Tinley Manor"],
    Pinetown: ["Pinetown CBD", "New Germany", "Sarnia", "Pinelands", "Ashley", "Westmead"],
    Chatsworth: ["Chatsworth CBD", "Bayview", "Moorton", "Westcliff", "Croftdene", "Arena Park"],
    Ladysmith: ["Ladysmith CBD", "Ezakheni", "Steadville", "Limit Hill"],
    "Port Shepstone": ["Port Shepstone CBD", "Marburg", "Shelly Beach", "Uvongo"],
    Margate: ["Margate CBD", "Ramsgate", "Southbroom", "San Lameer"],
    Scottburgh: ["Scottburgh CBD", "Park Rynie", "Pennington", "Ifafa"],
  },

  /* ── Eastern Cape ───────────────────────────────────────── */
  "Eastern Cape": {
    "Port Elizabeth (Gqeberha)": [
      "Central",
      "Summerstrand",
      "Humewood",
      "Walmer",
      "Mill Park",
      "Newton Park",
      "Lorraine",
      "Sherwood",
      "Kabega Park",
      "Framesby",
      "Fernglen",
      "Uitenhage Road",
      "Motherwell",
      "KwaNobuhle",
      "Colchester",
      "Schauderville",
    ],
    "East London": [
      "East London CBD",
      "Vincent",
      "Beacon Bay",
      "Gonubie",
      "Nahoon",
      "Amalinda",
      "Mdantsane",
      "Cambridge",
      "Quigney",
      "Berea",
    ],
    Mthatha: ["Mthatha CBD", "Norwood", "Hill View", "Ngangelizwe"],
    Bhisho: ["Bhisho CBD", "Bulembu", "Zwelitsha"],
    "Grahamstown (Makhanda)": ["Grahamstown CBD", "Oatlands", "Sunnyside", "Joza", "Fingo Village"],
    Queenstown: ["Queenstown CBD", "Ezibeleni", "Mlungisi"],
    "King Williams Town": ["King Williams Town CBD", "Bisho Extension", "Breidbach"],
    Cradock: ["Cradock CBD", "Lingelihle", "Michausdal"],
    Uitenhage: ["Uitenhage CBD", "Despatch", "KwaNobuhle", "Rosedale"],
  },

  /* ── Free State ─────────────────────────────────────────── */
  "Free State": {
    Bloemfontein: [
      "Bloemfontein CBD",
      "Westdene",
      "Universitas",
      "Langenhoven Park",
      "Brandwag",
      "Dan Pienaar",
      "Wilgehof",
      "Pellissier",
      "Fleurdal",
      "Batho",
      "Mangaung",
      "Heidedal",
      "Bloemanda",
    ],
    Welkom: ["Welkom CBD", "Thabong", "Bronville", "Riebeeckstad", "Dagbreek"],
    Kroonstad: ["Kroonstad CBD", "Maokeng", "Brentpark"],
    Bethlehem: ["Bethlehem CBD", "Bohlokong", "Bakenpark"],
    Sasolburg: ["Sasolburg CBD", "Zamdela", "Vaalpark"],
    Parys: ["Parys CBD", "Tumahole", "Schoemansville"],
    Virginia: ["Virginia CBD", "Meloding", "Merriespruit"],
    Phuthaditjhaba: ["Phuthaditjhaba CBD", "Makoaneng", "Namahali"],
  },

  /* ── Mpumalanga ─────────────────────────────────────────── */
  Mpumalanga: {
    "Mbombela (Nelspruit)": [
      "Nelspruit CBD",
      "Sonheuwel",
      "West Acres",
      "Steiltes",
      "Riverside Park",
      "Mpumalanga Mall area",
      "KaBokweni",
      "Msogwaba",
    ],
    "Witbank (Emalahleni)": [
      "Witbank CBD",
      "Tasbet Park",
      "Die Heuwel",
      "Klipfontein",
      "Ackerville",
      "KwaGuqa",
    ],
    Secunda: ["Secunda CBD", "Evander", "Trichardt", "Secunda Extension"],
    Middelburg: ["Middelburg CBD", "Mhluzi", "Aerorand", "Kanonkop"],
    "White River": ["White River CBD", "Riverside", "Rocky Drift", "Hazyview"],
    Barberton: ["Barberton CBD", "Emjindini", "Sheba"],
    Standerton: ["Standerton CBD", "Sakhile", "Kosmos"],
    Ermelo: ["Ermelo CBD", "Wesselton", "Cassim Park"],
  },

  /* ── Limpopo ────────────────────────────────────────────── */
  Limpopo: {
    Polokwane: [
      "Polokwane CBD",
      "Bendor",
      "Fauna Park",
      "Ivy Park",
      "Nirvana",
      "Westernburg",
      "Seshego",
      "Mankweng",
    ],
    Tzaneen: ["Tzaneen CBD", "Lenyenye", "Dan", "Nkowankowa"],
    Mokopane: ["Mokopane CBD", "Mahwelereng", "Mokopane Extension"],
    Musina: ["Musina CBD", "Nancefield"],
    "Louis Trichardt": ["Louis Trichardt CBD", "Makhado", "Eltivillas"],
    Thohoyandou: ["Thohoyandou CBD", "Shayandima", "Sibasa"],
    Phalaborwa: ["Phalaborwa CBD", "Namakgale", "Lulekani"],
    Lephalale: ["Lephalale CBD", "Onverwacht", "Marapong"],
  },

  /* ── North West ──────────────────────────────────────────── */
  "North West": {
    Rustenburg: [
      "Rustenburg CBD",
      "Cashan",
      "Safari Gardens",
      "Geelhout Park",
      "Boitekong",
      "Phokeng",
      "Tlhabane",
    ],
    Mahikeng: ["Mahikeng CBD", "Riviera Park", "Imperial Reserve", "Mmabatho"],
    "Potchefstroom (Tlokwe)": [
      "Potchefstroom CBD",
      "Bult",
      "Mooivallei",
      "Ikageng",
      "Promosa",
      "Miederpark",
    ],
    Klerksdorp: ["Klerksdorp CBD", "Wilkoppies", "Flamwood", "Jouberton"],
    Brits: ["Brits CBD", "Oukasie", "Primindia"],
    "Sun City": ["Sun City Resort"],
    Hartbeespoort: ["Hartbeespoort CBD", "Ifafi", "Melodie", "Meerhof", "Schoemansville"],
    Lichtenburg: ["Lichtenburg CBD", "Boikhutso"],
  },

  /* ── Northern Cape ──────────────────────────────────────── */
  "Northern Cape": {
    Kimberley: [
      "Kimberley CBD",
      "Beaconsfield",
      "Belgravia",
      "Hadison Park",
      "Monument Heights",
      "Galeshewe",
      "Homevale",
    ],
    Upington: ["Upington CBD", "Paballelo", "Progress"],
    Springbok: ["Springbok CBD", "Bergsig", "Matjieskloof"],
    "De Aar": ["De Aar CBD", "Nonzwakazi"],
    Kuruman: ["Kuruman CBD", "Wrenchville", "Mothibistad"],
    Kathu: ["Kathu CBD", "Kathu Extension", "Sesheng"],
  },
};

/**
 * Return suggested towns / suburbs for the given province + city.
 * Returns an empty array for unknown combinations — the user can
 * still type any value via the free-text combobox.
 */
export function getTownsForCity(province: string, city: string): string[] {
  return SA_TOWNS[province]?.[city] ?? [];
}
