/**
 * South African vehicle makes and their models.
 * Sourced from the SA new and used vehicle market (2024–2025).
 * Each make has an array of models commonly sold/listed in South Africa.
 * An "Other" option exists for both makes and models to allow custom entry.
 */

export interface VehicleMake {
  make: string;
  models: string[];
}

export const SA_VEHICLE_MAKES: VehicleMake[] = [
  {
    make: "Toyota",
    models: [
      "Hilux",
      "Fortuner",
      "Corolla Cross",
      "Starlet",
      "Corolla",
      "Corolla Hatch",
      "RAV4",
      "Land Cruiser 300",
      "Land Cruiser Prado",
      "Land Cruiser 76",
      "Land Cruiser 79",
      "Rumion",
      "Urban Cruiser",
      "Vitz",
      "Starlet Cross",
      "Hiace",
      "Quantum",
      "Avanza",
      "Rush",
      "Yaris",
      "GR Yaris",
      "GR Corolla",
      "GR86",
      "Supra",
      "Agya",
    ],
  },
  {
    make: "Volkswagen",
    models: [
      "Polo",
      "Polo Vivo",
      "Polo Sedan",
      "Golf",
      "Golf GTI",
      "Golf R",
      "T-Cross",
      "T-Roc",
      "Taigo",
      "Tiguan",
      "Tiguan Allspace",
      "Touareg",
      "Tayron",
      "Amarok",
      "Caddy",
      "Caravelle",
      "Kombi",
      "Transporter",
      "Crafter",
      "ID.4",
    ],
  },
  {
    make: "Suzuki",
    models: [
      "Swift",
      "Swift Sport",
      "Baleno",
      "Celerio",
      "S-Presso",
      "Ignis",
      "Dzire",
      "Ciaz",
      "Fronx",
      "Vitara",
      "Grand Vitara",
      "Jimny",
      "Jimny 5-Door",
      "Ertiga",
      "XL6",
      "Super Carry",
      "Eeco",
    ],
  },
  {
    make: "Ford",
    models: [
      "Ranger",
      "Ranger Raptor",
      "Everest",
      "Puma",
      "Territory",
      "EcoSport",
      "Mustang",
      "Tourneo Custom",
      "Transit",
      "Transit Custom",
      "Figo",
    ],
  },
  {
    make: "Hyundai",
    models: [
      "Grand i10",
      "Grand i10 Sedan",
      "i20",
      "i30 N",
      "Exter",
      "Venue",
      "Creta",
      "Grand Creta",
      "Alcazar",
      "Tucson",
      "Kona",
      "Kona N",
      "Santa Fe",
      "Palisade",
      "Staria",
      "H-100",
    ],
  },
  {
    make: "Isuzu",
    models: ["D-Max", "D-Max X-Rider", "MU-X", "KB"],
  },
  {
    make: "Nissan",
    models: [
      "Magnite",
      "Navara",
      "NP200",
      "NP300",
      "X-Trail",
      "Qashqai",
      "Patrol",
      "Micra",
      "Almera",
      "NV350",
    ],
  },
  {
    make: "BMW",
    models: [
      "1 Series",
      "2 Series",
      "2 Series Gran Coupe",
      "3 Series",
      "4 Series",
      "4 Series Gran Coupe",
      "5 Series",
      "7 Series",
      "8 Series",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "XM",
      "Z4",
      "i4",
      "i5",
      "i7",
      "iX",
      "iX1",
      "iX3",
      "M2",
      "M3",
      "M4",
      "M5",
      "M8",
    ],
  },
  {
    make: "Mercedes-Benz",
    models: [
      "A-Class",
      "B-Class",
      "C-Class",
      "CLA",
      "CLE",
      "E-Class",
      "S-Class",
      "GLA",
      "GLB",
      "GLC",
      "GLC Coupe",
      "GLE",
      "GLE Coupe",
      "GLS",
      "G-Class",
      "EQA",
      "EQB",
      "EQC",
      "EQE",
      "EQS",
      "AMG GT",
      "Vito",
      "Sprinter",
      "X-Class",
    ],
  },
  {
    make: "Audi",
    models: [
      "A1",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3",
      "Q5",
      "Q7",
      "Q8",
      "e-tron",
      "e-tron GT",
      "Q4 e-tron",
      "Q6 e-tron",
      "RS3",
      "RS5",
      "RS6",
      "RS7",
      "S3",
      "S5",
      "SQ5",
      "TT",
    ],
  },
  {
    make: "Kia",
    models: [
      "Picanto",
      "Pegas",
      "Rio",
      "Cerato",
      "Sonet",
      "Seltos",
      "Sportage",
      "Sorento",
      "Carnival",
      "EV6",
      "K2500",
      "K2700",
    ],
  },
  {
    make: "Renault",
    models: [
      "Kwid",
      "Triber",
      "Kiger",
      "Clio",
      "Captur",
      "Duster",
      "Arkana",
      "Koleos",
      "Megane",
      "Trafic",
      "Master",
    ],
  },
  {
    make: "Honda",
    models: [
      "Amaze",
      "Fit",
      "Jazz",
      "Civic",
      "Civic Type R",
      "HR-V",
      "CR-V",
      "BR-V",
      "WR-V",
      "Ballade",
      "Elevate",
    ],
  },
  {
    make: "Mazda",
    models: ["Mazda2", "Mazda3", "CX-3", "CX-30", "CX-5", "CX-60", "CX-80", "MX-5", "BT-50"],
  },
  {
    make: "Chery",
    models: ["Tiggo 4 Pro", "Tiggo 7 Pro", "Tiggo 8 Pro", "Tiggo 9 Pro", "Tiggo Cross"],
  },
  {
    make: "GWM",
    models: ["P-Series", "P300", "P500", "Steed"],
  },
  {
    make: "Haval",
    models: ["Jolion", "Jolion Pro", "H6", "H6 GT", "H7"],
  },
  {
    make: "Tank",
    models: ["Tank 300", "Tank 500"],
  },
  {
    make: "Omoda",
    models: ["C5", "C7", "C9", "E5"],
  },
  {
    make: "Jaecoo",
    models: ["J5", "J6", "J7", "J8"],
  },
  {
    make: "Mahindra",
    models: [
      "Pik Up",
      "Scorpio",
      "Scorpio-N",
      "XUV300",
      "XUV700",
      "XUV500",
      "Bolero",
      "KUV100",
      "Thar",
    ],
  },
  {
    make: "Peugeot",
    models: ["208", "2008", "308", "3008", "5008", "508", "Landtrek"],
  },
  {
    make: "Volvo",
    models: ["XC40", "XC60", "XC90", "S60", "S90", "V60", "C40", "EX30", "EX90"],
  },
  {
    make: "Jeep",
    models: [
      "Renegade",
      "Compass",
      "Cherokee",
      "Grand Cherokee",
      "Wrangler",
      "Gladiator",
      "Avenger",
    ],
  },
  {
    make: "Land Rover",
    models: [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Range Rover",
      "Range Rover Sport",
      "Range Rover Velar",
      "Range Rover Evoque",
    ],
  },
  {
    make: "TATA",
    models: ["Xenon", "Ultra", "Prima"],
  },
  {
    make: "Mitsubishi",
    models: ["Triton", "Pajero Sport", "Xpander", "Eclipse Cross", "ASX", "Outlander"],
  },
  {
    make: "Subaru",
    models: ["XV", "Forester", "Outback", "WRX", "BRZ", "Crosstrek"],
  },
  {
    make: "Opel",
    models: ["Corsa", "Crossland", "Grandland", "Mokka", "Combo"],
  },
  {
    make: "Fiat",
    models: ["500", "Tipo", "Panda", "Doblo", "Fiorino"],
  },
  {
    make: "Porsche",
    models: ["Cayenne", "Macan", "911", "Taycan", "Panamera", "718"],
  },
  {
    make: "Mini",
    models: ["Cooper", "Cooper S", "Countryman", "Clubman", "John Cooper Works"],
  },
  {
    make: "Lexus",
    models: ["NX", "RX", "UX", "IS", "ES", "LX", "LC"],
  },
  {
    make: "JAC",
    models: ["T6", "T8", "S2", "S4", "N-Series"],
  },
  {
    make: "BAIC",
    models: ["D20", "X25", "X55", "X65", "Beijing"],
  },
  {
    make: "Other",
    models: [],
  },
];

/**
 * Get all make names for dropdowns.
 */
export function getVehicleMakeNames(): string[] {
  return SA_VEHICLE_MAKES.map((v) => v.make);
}

/**
 * Get models for a given make. Returns empty array for unknown makes.
 */
export function getModelsForMake(make: string): string[] {
  const entry = SA_VEHICLE_MAKES.find((v) => v.make === make);
  return entry?.models ?? [];
}
